[package]
name = "jis0208"
version = "0.1.0"
authors = [ "Mikko Perttunen <cyndis@kapsi.fi>" ]

[lib]
name = "jis0208"
path = "lib.rs"

[dependencies.phf]
git = "git://github.com/sfackler/rust-phf"

[dependencies.phf_mac]
git = "git://github.com/sfackler/rust-phf"
